version: '3.8'

services:
  app:
    build:
      context: .
      target: development  # Use 'production' for production build
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/__pycache__
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - PORT=8000
    restart: unless-stopped
    # Uncomment the following for production
    # command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:8000

  # Uncomment to add a PostgreSQL database
  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: ${DB_USER:-postgres}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
  #     POSTGRES_DB: ${DB_NAME:-devprofile}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data:
