[build]
  command = "pip install -r requirements.txt && python -m spacy download en_core_web_sm"
  publish = "static"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[plugins]]
  package = "@netlify/plugin-python"
  [plugins.inputs]
    pythonVersion = "3.9"

[dev]
  framework = "#custom"
  targetPort = 8000
  command = "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
  publish = "static"
